#ifndef SD_HTTP_UPLOAD_UI_SECRETS_H
#define SD_HTTP_UPLOAD_UI_SECRETS_H

#define SD_HTTP_UPLOAD_TEST_SSID "Blacknet@Ueberlingen"
#define SD_HTTP_UPLOAD_TEST_PASSWORD "Ueberlingen2019"
#define SD_HTTP_UPLOAD_TEST_URL "http://192.168.0.37:8000/edit"

#endif // SD_HTTP_UPLOAD_UI_SECRETS_H
